apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinenetworkconfigs.kubevirtiphelper.k8s.binbash.org
spec:
  group: kubevirtiphelper.k8s.binbash.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vmname:
                  type: string
                  pattern: '^[\w-]+$'
                networkconfig:
                  type: array
                  items:
                    type: object
                    properties:
                      ipaddress:
                        type: string
                        pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
                      macaddress:
                        type: string
                        pattern: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'
                      networkname:
                        type: string
                        pattern: '^[\w\/-]+$'
            status:
              type: object
              properties:
                networkconfig:
                  type: array
                  items:
                    type: object
                    properties:
                      macaddress:
                        type: string
                        pattern: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'
                      networkname:
                        type: string
                        pattern: '^[\w\/-]+$'
                      status:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: virtualmachinenetworkconfigs
    singular: virtualmachinenetworkconfig
    kind: VirtualMachineNetworkConfig
    shortNames:
      - vmnetcfg
      - vmnetcfgs
