{{- if .Values.webhook.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevirt-ip-helper-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "kubevirt-ip-helper-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevirt-ip-helper-webhook.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubevirt-ip-helper-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevirt-ip-helper-webhook.fullname" . }}-cabundle
  namespace: "kube-system"
  labels:
    {{- include "kubevirt-ip-helper-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevirt-ip-helper-webhook.fullname" . }}-cabundle
subjects:
- kind: ServiceAccount
  name: {{ include "kubevirt-ip-helper-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
{{- end }}
