{{- if .Values.kubevirtiphelper.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubevirt-ip-helper.fullname" . }}
  labels:
    {{- include "kubevirt-ip-helper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubevirt-ip-helper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubevirt-ip-helper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
{{- end }}
