apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubevirt-ip-helper.fullname" . }}
  labels:
    {{- include "kubevirt-ip-helper.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["list", "watch"]
- apiGroups: ["kubevirtiphelper.k8s.binbash.org"]
  resources:
  - ippools
  - ippools/status
  - virtualmachinenetworkconfigs
  - virtualmachinenetworkconfigs/status
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["kubevirt.io"]
  resources:
  - virtualmachines
  verbs: ["get", "list", "watch"]
